name: Docker Deployment

env:
  DOCKER_IMAGE: "adridutta/Buy:latest"          
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }} 
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

on:
  push:
    branches:
      - main

jobs:

  docker_build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v3
        with: 
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
      - run: docker build -t $DOCKER_IMAGE .
      - run: docker push $DOCKER_IMAGE

  deploy:
    runs-on: ubuntu-latest
    needs: docker_build
    steps:
      - run: echo "Deploying to server"
      - run: docker pull $DOCKER_IMAGE
      - run: docker run -d $DOCKER_IMAGE
